const TOOL_ID="axm.map.object.receiver.packet";
const REQUEST_SCHEMA="axm.map-object-receiver-tool-request/v0.1";
const form=document.querySelector("#receiver-form"),slider=document.querySelector("#sample-slider"),sampleInput=document.querySelector("#sample-index"),buildButton=document.querySelector("#build-button"),serverState=document.querySelector("#server-state"),resultState=document.querySelector("#result-state"),emptyState=document.querySelector("#empty-state"),resultBox=document.querySelector("#result"),errorBox=document.querySelector("#error");
let latest={request:null,packet:null,receipt:null};
function boundedSample(value){const n=Number.parseInt(String(value),10);if(!Number.isInteger(n))return 40;return Math.max(0,Math.min(100,n))}
function syncSample(source){const n=boundedSample(source.value);slider.value=String(n);sampleInput.value=String(n)}
slider.addEventListener("input",()=>syncSample(slider));sampleInput.addEventListener("input",()=>syncSample(sampleInput));
function selected(name){return document.querySelector('input[name="'+name+'"]:checked').value}
function requestFromForm(){return{schema:REQUEST_SCHEMA,tool_id:TOOL_ID,sample_index:boundedSample(sampleInput.value),service_frame:selected("service_frame"),static_batching:selected("static_batching")}}
function setBadge(el,text,kind){el.textContent=text;el.className="badge "+kind}function pretty(value){return JSON.stringify(value,null,2)}
function downloadJson(kind){const value=latest[kind];if(!value)return;const blob=new Blob([pretty(value)+"\n"],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=kind+".json";a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll("[data-download]").forEach(button=>button.addEventListener("click",()=>downloadJson(button.dataset.download)));
document.querySelector("#reset-button").addEventListener("click",()=>{sampleInput.value="40";slider.value="40";document.querySelector('input[name="service_frame"][value="successor_20mm"]').checked=true;document.querySelector('input[name="static_batching"][value="current_sequence_static_24"]').checked=true});
async function checkServer(){try{const r=await fetch("/api/status",{cache:"no-store"});if(!r.ok)throw new Error("status "+r.status);const data=await r.json();serverState.textContent="loopback ready";serverState.classList.add("ready");if(data.layers&&data.layers.human!=="verified")serverState.textContent="human layer "+String(data.layers.human)}catch(error){serverState.textContent="server unavailable";serverState.classList.remove("ready")}}
checkServer();
form.addEventListener("submit",async event=>{event.preventDefault();const request=requestFromForm();latest.request=request;buildButton.disabled=true;buildButton.textContent="Building exact packet…";errorBox.hidden=true;resultBox.hidden=true;emptyState.hidden=true;setBadge(resultState,"running","idle");
try{const response=await fetch("/api/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(request)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||("request failed "+response.status));latest.packet=payload.packet;latest.receipt=payload.receipt;const packet=payload.packet,receipt=payload.receipt,frame=packet.environment_service_frame,runtime=packet.runtime_representation;
document.querySelector("#metric-time").textContent=packet.selection.time_s.toFixed(3)+" s";document.querySelector("#metric-lid").textContent=packet.selection.lid_target_rotation_deg_x.toFixed(1)+"°";document.querySelector("#metric-clearance").textContent=(Number(frame.minimum_inner_clearance_m)*1000).toFixed(3)+" mm";document.querySelector("#metric-surfaces").textContent=String(runtime.render_surface_count);
setBadge(document.querySelector("#clearance-badge"),frame.meets_60mm_contract?"60 mm clearance met":"historical clearance miss",frame.meets_60mm_contract?"pass":"warn");setBadge(document.querySelector("#batch-badge"),runtime.mode==="current_sequence_static_24"?"7 moving / 24 static":"unbatched receiver",runtime.mode==="current_sequence_static_24"?"pass":"idle");
document.querySelector("#exact-head").textContent=receipt.exact_tool_head;document.querySelector("#holds").replaceChildren(...packet.holds.map(text=>{const li=document.createElement("li");li.textContent=text;return li}));document.querySelector("#request-json").textContent=pretty(request);document.querySelector("#packet-json").textContent=pretty(packet);document.querySelector("#receipt-json").textContent=pretty(receipt);resultBox.hidden=false;setBadge(resultState,receipt.result==="PASS_MAP_OBJECT_RECEIVER_PACKET"?"verified PASS":"receipt returned","pass")}
catch(error){errorBox.textContent=String(error.message||error);errorBox.hidden=false;setBadge(resultState,"failed","warn")}finally{buildButton.disabled=false;buildButton.textContent="Build receiver packet"}});
